events {
    worker_connections 1024;
}

http {

    upstream api_gateway_pool {
        least_conn;
        server api_gateway_1:8080;
        server api_gateway_2:8080;
    }

    upstream inventory_pool {
        least_conn;
        server inventory_1:8081;
        server inventory_2:8081;
    }

    upstream booking_pool {
        least_conn;
        server booking_1:8082;
        server booking_2:8082;
    }

    server {
        listen 80;

        # All client traffic enters here — API Gateway handles auth/rate limit
        location /api/book {
            proxy_pass         http://api_gateway_pool;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_next_upstream error timeout http_500 http_502 http_503;
            proxy_next_upstream_tries 2;
            proxy_connect_timeout 3s;
            proxy_read_timeout    10s;
        }

        # Internal routing — only reached after API Gateway forwards here
        location /api/reserve {
            proxy_pass         http://inventory_pool;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_500 http_502 http_503;
            proxy_next_upstream_tries 2;
            proxy_connect_timeout 3s;
            proxy_read_timeout    10s;
        }

        location /api/release {
            proxy_pass         http://inventory_pool;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_500 http_502 http_503;
            proxy_next_upstream_tries 2;
            proxy_connect_timeout 3s;
            proxy_read_timeout    10s;
        }

        location /api/bookings {
            proxy_pass         http://booking_pool;
            proxy_http_version 1.1;
            proxy_set_header   Connection "";
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_500 http_502 http_503;
            proxy_next_upstream_tries 2;
            proxy_connect_timeout 3s;
            proxy_read_timeout    10s;
        }

        location /health {
            access_log off;
            return 200 "ok\n";
            add_header Content-Type text/plain;
        }
    }
}